/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JTextField;

/**
 *
 * @author pamelamurillo
 */
public class MainFrame extends javax.swing.JFrame {
    
    private JTextField[] formComponents;
    private String defaultIMSNumberText = "Su IMS es de: ";
    private String defaultIMSStatusText = "Lo que le califica como: ";
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        btnReset.setOpaque(true);
        
        JTextField[] formComponents = {inputID, inputName, inputAge, inputWeight, inputHeight} ;
        
        this.formComponents = formComponents;
        
        
    }

    public void getIMS() {
        
    }
            
            
    public void resetForms() {
        for (int i = 0; i < formComponents.length; i++) {
            formComponents[i].setText("");
        }
        
        lblIMSNumber.setVisible(false);
        lblIMSStatus.setVisible(false);
    }
    
    public boolean confirmCorrectData(){
        boolean allCorrect = false;
        try {
            int idValue = Integer.parseInt( inputID.getText() );
            int ageValue = Integer.parseInt( inputAge.getText() );
            int weightValue = Integer.parseInt( inputWeight.getText() );
            int heightValue = Integer.parseInt( inputHeight.getText() );
            allCorrect = true;
            
        } catch (NumberFormatException ex){
            ex.printStackTrace();
        }
        
        return allCorrect;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIMSStatus = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblWeight1 = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        lblAge1 = new javax.swing.JLabel();
        lblAge2 = new javax.swing.JLabel();
        lblAge3 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        lblFillForm = new javax.swing.JLabel();
        lblIMSNumber = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        inputHeight = new javax.swing.JTextField();
        inputID = new javax.swing.JTextField();
        inputAge = new javax.swing.JTextField();
        inputWeight = new javax.swing.JTextField();
        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();
        lblCreator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIMSStatus.setFont(new java.awt.Font("Kailasa", 0, 28)); // NOI18N
        lblIMSStatus.setForeground(new java.awt.Color(0, 0, 0));
        lblIMSStatus.setText("Lo que le califica como:");
        jPanel1.add(lblIMSStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 500, -1));

        lblWelcome.setFont(new java.awt.Font("Kailasa", 1, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 0, 0));
        lblWelcome.setText("Bienvenido Usuario");
        jPanel1.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lblID.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setText("Cédula: ");
        jPanel1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        lblName.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText("Nombre:");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        lblHeight.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblHeight.setForeground(new java.awt.Color(0, 0, 0));
        lblHeight.setText("Altura:");
        jPanel1.add(lblHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        lblAge.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblAge.setForeground(new java.awt.Color(0, 0, 0));
        lblAge.setText("m");
        jPanel1.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        lblWeight1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblWeight1.setForeground(new java.awt.Color(0, 0, 0));
        lblWeight1.setText("Peso: ");
        jPanel1.add(lblWeight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        inputName.setBackground(new java.awt.Color(245, 245, 245));
        inputName.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });
        jPanel1.add(inputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 250, 30));

        lblAge1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblAge1.setForeground(new java.awt.Color(0, 0, 0));
        lblAge1.setText("Edad:");
        jPanel1.add(lblAge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        lblAge2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblAge2.setForeground(new java.awt.Color(0, 0, 0));
        lblAge2.setText("años");
        jPanel1.add(lblAge2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        lblAge3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblAge3.setForeground(new java.awt.Color(0, 0, 0));
        lblAge3.setText("kg");
        jPanel1.add(lblAge3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));

        lblError.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 3, 13)); // NOI18N
        lblError.setForeground(new java.awt.Color(204, 0, 0));
        lblError.setText("Alguno de los datos no ha sido rellenado correctamente");
        jPanel1.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 370, 40));

        lblFillForm.setFont(new java.awt.Font("Kailasa", 0, 28)); // NOI18N
        lblFillForm.setForeground(new java.awt.Color(0, 0, 0));
        lblFillForm.setText("Para poder averiguar su IMS, rellene el siguiente formulario");
        jPanel1.add(lblFillForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        lblIMSNumber.setFont(new java.awt.Font("Kailasa", 0, 28)); // NOI18N
        lblIMSNumber.setForeground(new java.awt.Color(0, 0, 0));
        lblIMSNumber.setText("Su IMS es de: ");
        jPanel1.add(lblIMSNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 500, -1));

        btnReset.setBackground(new java.awt.Color(0, 153, 153));
        btnReset.setFont(new java.awt.Font("Kailasa", 0, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reiniciar Datos");
        btnReset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, 190, 50));

        btnConfirm.setBackground(new java.awt.Color(0, 153, 153));
        btnConfirm.setFont(new java.awt.Font("Kailasa", 0, 18)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("Confirmar");
        btnConfirm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 190, 50));

        inputHeight.setBackground(new java.awt.Color(245, 245, 245));
        inputHeight.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        inputHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputHeightActionPerformed(evt);
            }
        });
        jPanel1.add(inputHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 180, 30));

        inputID.setBackground(new java.awt.Color(245, 245, 245));
        inputID.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        inputID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIDActionPerformed(evt);
            }
        });
        jPanel1.add(inputID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 250, 30));

        inputAge.setBackground(new java.awt.Color(245, 245, 245));
        inputAge.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        inputAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAgeActionPerformed(evt);
            }
        });
        jPanel1.add(inputAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 180, 30));

        inputWeight.setBackground(new java.awt.Color(245, 245, 245));
        inputWeight.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        inputWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputWeightActionPerformed(evt);
            }
        });
        jPanel1.add(inputWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 180, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1100, 580));

        pnlHeader.setBackground(new java.awt.Color(0, 102, 102));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("WeightLess");
        pnlHeader.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 99));

        lblSubtitle.setFont(new java.awt.Font("Hiragino Mincho ProN", 2, 18)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(242, 242, 242));
        lblSubtitle.setText("\"Saber tu cuerpo es saber cuidarte\"");
        pnlHeader.add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 130));

        pnlFooter.setBackground(new java.awt.Color(0, 102, 102));
        pnlFooter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreator.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 12)); // NOI18N
        lblCreator.setForeground(new java.awt.Color(255, 255, 255));
        lblCreator.setText("Murillo Anchia Pamela");
        pnlFooter.add(lblCreator, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        getContentPane().add(pnlFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 1100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed

        if ( confirmCorrectData() ) {
            getIMS();
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetForms();
    }//GEN-LAST:event_btnResetActionPerformed

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void inputHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputHeightActionPerformed

    private void inputIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIDActionPerformed

    private void inputAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAgeActionPerformed

    private void inputWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputWeightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField inputAge;
    private javax.swing.JTextField inputHeight;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputWeight;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAge1;
    private javax.swing.JLabel lblAge2;
    private javax.swing.JLabel lblAge3;
    private javax.swing.JLabel lblCreator;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFillForm;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIMSNumber;
    private javax.swing.JLabel lblIMSStatus;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWeight1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    // End of variables declaration//GEN-END:variables
}
